DELETE FROM Person;

insert into person (name, age, gender) values ('Shandee Tatters', 30, 'Male');
insert into person (name, age, gender) values ('Sylas Northall', 32, 'Male');
insert into person (name, age, gender) values ('Leanora McGow', 72, 'Female');
insert into person (name, age, gender) values ('Taryn Alekseev', 35, 'Female');
insert into person (name, age, gender) values ('Norma Buntin', 44, 'Female');
insert into person (name, age, gender) values ('Cissy Larmett', 45, 'Female');
insert into person (name, age, gender) values ('Janelle Nuccii', 49, 'Female');
insert into person (name, age, gender) values ('Vite Cucuzza', 29, 'Male');
insert into person (name, age, gender) values ('Briggs Burdas', 49, 'Male');
insert into person (name, age, gender) values ('Marylin Blazek', 51, 'Female');
insert into person (name, age, gender) values ('Sofia Barrar', 43, 'Female');
insert into person (name, age, gender) values ('Farra Devey', 25, 'Female');
insert into person (name, age, gender) values ('Evelin Fairlaw', 61, 'Male');
insert into person (name, age, gender) values ('Alanson Iannelli', 71, 'Male');
insert into person (name, age, gender) values ('Chris Garcia', 32, 'Male');
insert into person (name, age, gender) values ('Guillermo McKeighen', 55, 'Male');
insert into person (name, age, gender) values ('Cliff Ruby', 27, 'Male');
insert into person (name, age, gender) values ('Luis Braunstein', 64, 'Male');
insert into person (name, age, gender) values ('Anet Czajka', 26, 'Female');
insert into person (name, age, gender) values ('Eda Houlison', 69, 'Female');